services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: murmer
      POSTGRES_PASSWORD: murmer
      POSTGRES_DB: murmer
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: ./murmer_server
    restart: unless-stopped
    # Load optional settings like ADMIN_TOKEN from a `.env` file
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://murmer:murmer@db:5432/murmer
      UPLOAD_DIR: /app/uploads
      # Uncomment to require a password for WebSocket connections
      # SERVER_PASSWORD: changeme
      # Rate limiting configuration
      MAX_MESSAGES_PER_MINUTE: 300
      MAX_AUTH_ATTEMPTS_PER_MINUTE: 5
      NONCE_EXPIRY_SECONDS: 300
      # Allow the desktop client dev server to access the HTTP endpoints during development
      CORS_ALLOW_ORIGINS: http://localhost:1420
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:3001/"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
volumes:
  db_data:
  uploads:
