services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: murmer
      POSTGRES_PASSWORD: murmer
      POSTGRES_DB: murmer
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: Sicheres
      MINIO_ROOT_PASSWORD: Passwort
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  server:
    build: ./murmer_server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://murmer:murmer@db:5432/murmer
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: murmer
      MINIO_PUBLIC_URL: http://localhost:9000
      AWS_ACCESS_KEY_ID: Sicheres
      AWS_SECRET_ACCESS_KEY: Passwort
      AWS_REGION: us-east-1
    depends_on:
      - db
      - minio
    ports:
      - "3001:3001"
volumes:
  db_data:
  minio_data:
