services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: murmer
      POSTGRES_PASSWORD: murmer
      POSTGRES_DB: murmer
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build: ./murmer_server
    restart: unless-stopped
    # Load optional settings like ADMIN_TOKEN from a `.env` file
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://murmer:murmer@db:5432/murmer
      UPLOAD_DIR: /app/uploads
      # Uncomment to require a password for WebSocket connections
      # SERVER_PASSWORD: changeme
      # Rate limiting configuration
      MAX_MESSAGES_PER_MINUTE: 300
      MAX_AUTH_ATTEMPTS_PER_MINUTE: 5
      NONCE_EXPIRY_SECONDS: 300
      # Enable CORS for development (comment out for production)
      ENABLE_CORS: "1"
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
volumes:
  db_data:
  uploads:
