[package]
name = "murmer_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["ws", "multipart"] }
tokio = { version = "1", features = ["full"] }
hyper = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
futures = "0.3"
tokio-postgres = "0.7"
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
