[package]
name = "murmer_server"
version = "2025.7.12-alpha.1"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws", "multipart"] }
tokio = { version = "1", features = ["full"] }
hyper = "1"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
futures = "0.3"
tokio-postgres = "0.7.13"
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tower-http = { version = "0.6.6", features = ["fs", "cors"] }
ed25519-dalek = { version = "2", features = ["rand_core","serde"] }
rand = "0.8"
hex = "0.4"
