name: Deploy to VPS

on:
  release:
    types: [published] # Trigger when a release is published
  workflow_dispatch: # Allow manual trigger too

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 116.203.92.70
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22 # change if your SSH uses a different port
          script: |
            echo "Changing to project directory..."
            cd /root/Murmer/murmer_server

            echo "Pulling latest changes from master..."
            git pull

            echo "Rebuilding and starting Docker containers..."
            docker compose up --build -d

            echo "Deployment successful 🎉"
